name: consumer-tonic-ui-dist

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    permissions: write-all
    name: deploy plugin
    runs-on: ebf-pod-ubuntu-2004@${{ github.run_id }}-dev
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Check Node version
        run: node -v

      - name: build dist
        run: |
          npm i
          npm run build

      - name: deploy
        if: ${{ github.ref == 'refs/heads/dev' }} # only deploy dev
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          node publish.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
