name: consumer-tonic-ui-dist

on:
  workflow_dispatch:
  push:
    branches:
      - temp

jobs:
  build:
    name: deploy plugin
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: temp

      - name: Check Node version
        run: node -v

      - name: build dist
        run: |
          npm i
          npm run build

      - name: deploy
        if: ${{ github.ref == 'refs/heads/temp' }} # only deploy temp
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          node publish.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
