name: consumer-tonic-ui-dist

on:
  workflow_dispatch:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  plugin:
    name: deploy plugin
    runs-on: ebf-pod-ubuntu-2004@${{ github.run_id }}-plugin
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check Node version
        run: node -v

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Create tag env
        id: tag
        run: echo "TAG=v$(node -e "console.log(require('./dist-package.json').version)")-${{ steps.extract_branch.outputs.branch }}.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: build dist
        run: |
          npm i
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Show info in annotation
        run: |
          echo "Running some code..."

          # Example of an error annotation
          if [[ -f some-file.txt ]]; then
            echo "::error file=some-file.txt,line=10,col=5::File not found error"
          fi

          # Example of a warning annotation
          echo "::warning npm version `0.0.8-alpha.${{ github.run_number }}`::This is a warning message"

          # Example of a notice annotation
          echo "::notice file=another-file.txt,line=30,col=15::This is a notice message"

      - name: Setup specific version # version specific version - https://stackoverflow.com/questions/48423867/npm-version-update-to-specific-version
        run: |
          cd dist
          npm version "0.0.8-alpha.${{ github.run_number }}" --no-git-tag-version
          npm publish --access=public --tag=experimental
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
