name: consumer-tonic-ui-ghpage

on:
  workflow_dispatch:
#  push:
#    branches:
#      - dev

permissions:
  id-token: read
  contents: write

jobs:
  build:
    name: gh-page for doc
    runs-on: ebf-pod-ubuntu-2004@${{ github.run_id }}-dev
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check Node version
        run: node -v

      - name: Setup SSH Permission
        uses: actions/ssh-config@v1
        with:
          config_dir: .ssh
          ssh_key: ${{ secrets.SERVICE_ACCOUNT_SSH_KEY }}

      - name: Default SSH Config Setting
        shell: bash
        run: |
          touch ~/.ssh/config
          printf "Host *\n\tStrictHostKeyChecking no\n\tIdentityFile ${{ env.SSH_KEY_FILE }}\n\tLogLevel ERROR\n" >> ~/.ssh/config
          cat ~/.ssh/config
          git ls-remote --refs ssh://git@adc.github.trendmicro.com:Consumer-Frontend/consumer-tonic-design-system.git web-dist

      - name: build astro
        run: |
          cd astro
          npm i
          npm run astro:build

      - name: deploy
        if: ${{ github.ref == 'refs/heads/dev' }} # only deploy dev
        run: node ghpahes.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

