name: consumer-tonic-ui-ghpage

on:
  workflow_dispatch:
#  push:
#    branches:
#      - dev

permissions:
  id-token: read
  contents: write

jobs:
  build:
    name: gh-page for doc
    runs-on: ebf-pod-ubuntu-2004@${{ github.run_id }}-dev
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check Node version
        run: node -v

      - name: build astro
        run: |
          cd astro
          npm i
          npm run astro:build

      - name: deploy
        if: ${{ github.ref == 'refs/heads/dev' }} # only deploy dev
        run: node ghpahes.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

