name: consumer-tonic-ui-dist

on:
  workflow_dispatch:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: write

jobs:
  plugin:
    name: deploy plugin
    runs-on: ebf-pod-ubuntu-2004@${{ github.run_id }}-plugin
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: test install
        run: npm i -s "git+https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@adc.github.trendmicro.com/Consumer-Frontend/consumer-tonic-design-system.git#web-dist"
